title: "Sample-efficient Cross-Entropy Method for Real-time Planning"
description: Supplementary Website

username: sample-efficient-cross-entropy
email: sample.efficient.cross.entropy@gmail.com

authors: "Anonymous Author(s)"
